spring.application.name=SpringBoot-Thymeleaf-WebApp

#MYSQL
spring.datasource.url= jdbc:mysql://localhost:3306/SB_TL_WEBAPP?createDatabaseIfNotExist=true
spring.datasource.username= root
spring.datasource.password= root

#JPA
spring.jpa.hibernate.ddl-auto= update
spring.jpa.show-sql= true
spring.jpa.open-in-view= true
